[tool.poetry]
authors = ["Eliot Courtney <edgeworth.dev@gmail.com>"]
classifiers = ["License :: OSI Approved :: GPL-3.0-only"]
description = "memerna"
name = "memerna"
readme = "README.md"
version = "0.1.0"

[tool.poetry.dependencies]
bidict = "*"
click = "*"
click_log = "*"
cloup = "*"
python = "^3.10"
torch = "*"
torch-tb-profiler = "*"

[tool.poetry.dev-dependencies]
black = "*"
mypy = "*"
prospector = "*"

[tool.mypy]
show_column_numbers = true
# Require type hints
disallow_untyped_defs = true

# Allow types that is not imported to be used in annotations.
# This is necessary because some libraries don't have annotations.
disallow_any_unimported = false

# Disallow implicit optional e.g. arg: str = None
no_implicit_optional = true

# Check bodies of functions without type annotations too
check_untyped_defs = true

# Warn about returning Any from a function annotated to not return it
warn_return_any = true

# Warn about unused ignore annotations
warn_unused_ignores = true

# Show error codes
show_error_codes = true

# Set python version.
python_version = '3.10'

# No type hints for torchvision.
[[tool.mypy.overrides]]
ignore_missing_imports = true
module = ["torchvision.*", "torchtext.*", "click_log.*", "numpy.*", "RNA.*"]

[tool.black]
line-length = 100
target-version = ['py310']

[tool.pylint.format]
max-line-length = 100

[tool.pylint.typecheck]
generated-members = "numpy.*,torch.*"

[tool.pylint.messages_control]
# Fix "not callable" errors for torch.nn.Module subclasses
# Want to use f-strings in logging
# unsubscriptable-object: Fix false positive on bimap indexing
disable = ["not-callable", "logging-fstring-interpolation", "unsubscriptable-object"]
