// Copyright 2016 E.
#include <cstdlib>

#include "common_test.h"
#include "model/context.h"
#include "model/parsing.h"

namespace mrna::mfe {

class MfeAlgTest : public testing::TestWithParam<ModelCfg::TableAlg> {
 public:
  Energy Mfe(const std::string& s) {
    return std::get<Computed>(Context(StringToPrimary(s), g_em, ModelCfg(GetParam())).Fold())
        .energy;
  }
};

TEST_P(MfeAlgTest, T04) {
  ONLY_FOR_THIS_MODEL(g_em, T04_MODEL_HASH);

  EXPECT_EQ(-45, Mfe("GGGGAAACCCC"));
  EXPECT_EQ(-51, Mfe("UUGAAAAGCGGUUCCGUUCAGUCCUACUCACACGUCCGUCACACAUUAUGCCGGUAGAUA"));
  EXPECT_EQ(-133, Mfe("AAAAACUAGCAUCUAGUGGGCUCCCGAUCGCCUCCUUCUCGUAUUACGUUAAUGCAACUCAAGUGAGCCCGU"));
  EXPECT_EQ(-57, Mfe("AAAUUCCGCUUGACAGCUCGCCACAACGGCAGGAC"));
  EXPECT_EQ(-121, Mfe("ACCGUCAGCUACCGCCGACUAUACUCUUUAGUCAGACGGGG"));
  EXPECT_EQ(-74, Mfe("CACACUCCCGCAAAUGCCGAGUAUCAGAUUACUCCCCGGG"));
  EXPECT_EQ(-32, Mfe("CCCAACGGAGUAACUUAGCGAAUAGCAGGGG"));
  EXPECT_EQ(-40, Mfe("CCGAAGGGGCUGCGGCG"));
  EXPECT_EQ(-120, Mfe("CCGGGCCAGCCCGCUCCUACGGGGGGUC"));
  EXPECT_EQ(-74, Mfe("CCGUAAAGUCGAACCAGACGUGCAUGAGCAAGCGG"));
  EXPECT_EQ(-6, Mfe("CCUCCGGG"));
  EXPECT_EQ(-30, Mfe("CCUGGAUAUUCCGAUGAGCACGUGCGAGGGC"));
  EXPECT_EQ(-65, Mfe("CGCAGGGUCGGACCCGGGAGAACCGCGA"));
  EXPECT_EQ(-60, Mfe("CGCUUAAGGCUAUUUGGCCGGAUCUCCAAGGCA"));
  EXPECT_EQ(-6, Mfe("CGGAAACGG"));
  EXPECT_EQ(-22, Mfe("CUGAAACUGGAAACAGAAAUG"));
  EXPECT_EQ(-12, Mfe("CUUAUAGUUAAGG"));
  EXPECT_EQ(-122, Mfe("GAUGAGGGGAAACGGUGACUGGGACUCAGACAACGAUAGCAGCCAAAUAGGGAAGCUUCCUUC"));
  EXPECT_EQ(-29, Mfe("GCCAAGGCCCCACCCGGA"));
  EXPECT_EQ(-39, Mfe("GCCAGACAAACACGAUUCUUUGAUAGUACUGACUAUUCUACAAUUAGGCC"));
  EXPECT_EQ(-67, Mfe("GCGACCGGGGCUGGCUUGGUAAUGGUACUCCC"));
  EXPECT_EQ(
      -276, Mfe("GCGACCGGGGCUGGCUUGGUAAUGGUACUCCCCUGUCACGGGAGAGAAUGUGGGUUCAAAUCCCAUCGGUCGCGCCA"));
  EXPECT_EQ(-53, Mfe("GCGCCCCAGUCGACGCUGAGCUCCUCUGCU"));
  EXPECT_EQ(-157, Mfe("GGCACAUACUGGGACAACAUUCGUUGGGUUCCCGGGUCGAACGGCAGCCG"));
  EXPECT_EQ(-49, Mfe("GGCCGAUGGCAGCGAUAGC"));
  EXPECT_EQ(-44, Mfe("GGCGCACGCGUUAGCCGGGGAUCCACAGUGC"));
  EXPECT_EQ(-45, Mfe("GGGGAAACCCC"));
  EXPECT_EQ(-29, Mfe("GUCAUGCACUACUGCGAUUCAUACGGAAACAGACG"));
  EXPECT_EQ(-23, Mfe("UACCCUGUUCAGCAUUGGAAAUUUCCUGGG"));
  EXPECT_EQ(-80, Mfe("UCCACGGCUCGACGGCGCACUUAGUGCGUGGG"));
  EXPECT_EQ(-4, Mfe("UGCAAAGCAA"));
  EXPECT_EQ(-208, Mfe("UGGGGAAGUGCCGAUGCGGUACUAUUAUCCACUGUCUAUGGAUAAGUCCCCCGACCU"));
}

INSTANTIATE_TEST_SUITE_P(FoldAlgTest, MfeAlgTest, testing::ValuesIn(ModelCfg::TABLE_ALGS));

}  // namespace mrna::mfe
