// Copyright 2022 Eliot Courtney.
#include "compute/partition/partition.h"

#include <string>

#include "common_test.h"
#include "ctx/ctx.h"
#include "gtest/gtest.h"

namespace mrna::part {

class PartAlgTest : public testing::TestWithParam<ctx::CtxCfg::PartAlg> {
 public:
  PartResult Partition(const std::string& s) {
    return ctx::Ctx(t04, ctx::CtxCfg{.part_alg = GetParam()}).Partition(Primary::FromString(s));
  }
};

TEST_P(PartAlgTest, T04) {
  // TODO: Test these results. For now just run them.
  Partition("GGGGAAACCCC");
  Partition("UUGAAAAGCGGUUCCGUUCAGUCCUACUCACACGUCCGUCACACAUUAUGCCGGUAGAUA");
  Partition("AAAAACUAGCAUCUAGUGGGCUCCCGAUCGCCUCCUUCUCGUAUUACGUUAAUGCAACUCAAGUGAGCCCGU");
  Partition("AAAUUCCGCUUGACAGCUCGCCACAACGGCAGGAC");
  Partition("ACCGUCAGCUACCGCCGACUAUACUCUUUAGUCAGACGGGG");
  Partition("CACACUCCCGCAAAUGCCGAGUAUCAGAUUACUCCCCGGG");
  Partition("CCCAACGGAGUAACUUAGCGAAUAGCAGGGG");
  Partition("CCGAAGGGGCUGCGGCG");
  Partition("CCGGGCCAGCCCGCUCCUACGGGGGGUC");
  Partition("CCGUAAAGUCGAACCAGACGUGCAUGAGCAAGCGG");
  Partition("CCUCCGGG");
  Partition("CCUGGAUAUUCCGAUGAGCACGUGCGAGGGC");
  Partition("CGCAGGGUCGGACCCGGGAGAACCGCGA");
  Partition("CGCUUAAGGCUAUUUGGCCGGAUCUCCAAGGCA");
  Partition("CGGAAACGG");
  Partition("CUGAAACUGGAAACAGAAAUG");
  Partition("CUUAUAGUUAAGG");
  Partition("GAUGAGGGGAAACGGUGACUGGGACUCAGACAACGAUAGCAGCCAAAUAGGGAAGCUUCCUUC");
  Partition("GCCAAGGCCCCACCCGGA");
  Partition("GCCAGACAAACACGAUUCUUUGAUAGUACUGACUAUUCUACAAUUAGGCC");
  Partition("GCGACCGGGGCUGGCUUGGUAAUGGUACUCCC");
  Partition("GCGACCGGGGCUGGCUUGGUAAUGGUACUCCCCUGUCACGGGAGAGAAUGUGGGUUCAAAUCCCAUCGGUCGCGCCA");
  Partition("GCGCCCCAGUCGACGCUGAGCUCCUCUGCU");
  Partition("GGCACAUACUGGGACAACAUUCGUUGGGUUCCCGGGUCGAACGGCAGCCG");
  Partition("GGCCGAUGGCAGCGAUAGC");
  Partition("GGCGCACGCGUUAGCCGGGGAUCCACAGUGC");
  Partition("GGGGAAACCCC");
  Partition("GUCAUGCACUACUGCGAUUCAUACGGAAACAGACG");
  Partition("UACCCUGUUCAGCAUUGGAAAUUUCCUGGG");
  Partition("UCCACGGCUCGACGGCGCACUUAGUGCGUGGG");
  Partition("UGCAAAGCAA");
  Partition("UGGGGAAGUGCCGAUGCGGUACUAUUAUCCACUGUCUAUGGAUAAGUCCCCCGACCU");
}

INSTANTIATE_TEST_SUITE_P(PartAlgTest, PartAlgTest, testing::ValuesIn(ctx::CtxCfg::PART_ALGS));

}  // namespace mrna::part
